La pregunta que buscamos responder es:

¿Cuál ha sido el rendimiento electoral de las distintas coaliciones formadas por el Partido Peronista en cada una de las provincias de la República Argentina en la elecciones generales de medio término es en el periodo 2011-2023?

Decidimos tomar sólo las elecciones generales (y no las elecciones PASO) ya que lo buscamos entender es la intención del voto que ha tenido los electores al momento de tener que elegir 'firmemente' por su representación en el Congreso (y no metodo de termómetro electoral de cada espacio electoral)

In [ ]:
import pandas as pd

In [ ]:
elecciones=pd.read_csv("/content/datos_electorales_err.csv")

In [ ]:
elecciones.head(5)

,id,Elecciones,Partido,Porcentaje,Votos,Participacion,Electores,Votantes,Bancas
0,BUENOS AIRES,GENERALES 2011,FRENTE PARA LA VICTORIA,56.97,4460986.00,123.31,10574461,8693248,NaN
1,BUENOS AIRES,GENERALES 2011,FRENTE AMPLIO PROGRESISTA,13.01,1018572.00,82.21,10574461,8693248,NaN
2,BUENOS AIRES,GENERALES 2011,UNIÃ“N PARA EL DESARROLLO SOCIAL,11.56,905064.00,82.21,10574461,8693248,NaN
3,BUENOS AIRES,GENERALES 2011,BLANCO,9.25,804237.00,82.21,10574461,8693248,NaN
4,BUENOS AIRES,GENERALES 2011,FRENTE POPULAR,6.75,528789.00,82.21,10.574.461,8693248,NaN

In [ ]:
# elecciones = elecciones[elecciones["id"] == "LA PAMPA"] # This line was commented out to retain data for all provinces

In [ ]:
print("\nValores faltantes por columna:")
print(elecciones.isnull().sum())

Valores faltantes por columna:
id                  0
Elecciones          0
Partido             0
Porcentaje          0
Votos               5
Participacion       0
Electores           0
Votantes            0
Bancas           3044
dtype: int64

In [ ]:
print("\nRegistros periodo electoral:")
print(elecciones["Elecciones"].unique())

Registros periodo electoral:
['GENERALES 2011' 'GENERALES 2090' 'GENERALES 2013' 'GENERALES 2015'
 'GENERALES 2017' 'GENERALES 2019' 'GENERALES 2021' 'GENERALES 2023'
 'PASO 2011' 'PASO 2013' 'PASO 2090' 'PASO 2015' 'PASO 2017' 'PASO 2019'
 'PASO 2021' 'PASO 2023']

In [ ]:
print("\nRegistros provincias:")
print(elecciones["id"].unique())

Registros provincias:
['BUENOS AIRES' 'CATAMARCA' 'CHACO' 'CHUBUT'
 'CIUDAD AUTONOMA DE BUENOS AIRES' 'CORDOBA' 'cordoba' 'CORDOBA '
 'CORD OBA' 'Córdoba' 'CORRIENTES' 'ENTRE RIOS' 'FORMOSA' 'JUJUY'
 'LA PAMPA' 'LA RIOJA' 'MENDOZA' 'MISIONES' 'NEUQUEN' 'RIO NEGRO' 'SALTA'
 'SAN JUAN' 'SAN LUIS' 'SANTA CRUZ' 'SANTA FE' 'SANTIAGO DEL ESTERO'
 'TIERRA DEL FUEGO' 'TUCUMAN']

In [ ]:
print("\nRegistros partidos")
print(elecciones["Partido"].unique())

Registros partidos
['FRENTE PARA LA VICTORIA' 'FRENTE AMPLIO PROGRESISTA'
 'UNIÃ“N PARA EL DESARROLLO SOCIAL' 'BLANCO' 'FRENTE POPULAR'
 'COMPROMISO FEDERAL' 'FRENTE DE IZQUIERDA Y DE LOS TRABAJADORES'
 'COALICION CIVICA ARI' 'NULO' 'IMPUGNADO' 'FRENTE RENOVADOR'
 'FRENTE PROGRESISTA CIVICO Y SOCIAL'
 'UNIDOS POR LA LIBERTAD Y EL TRABAJO' 'UNION CON FE'
 'CAMBIEMOS BUENOS AIRES' 'UNIDOS POR UNA NUEVA ALTERNATIVA (UNA)'
 'PROGRESISTAS' 'UNIDAD CIUDADANA' '1PAIS' 'FRENTE JUSTICIALISTA'
 'FRENTE DE TODOS' 'JUNTOS POR EL CAMBIO' 'CONSENSO FEDERAL'
 'FRENTE DE IZQUIERDA Y DE TRABAJADORES - UNIDAD' 'JUNTOS'
 'AVANZA LIBERTAD' 'FRENTE VAMOS CON VOS' 'VALORES' 'UNION POR LA PATRIA'
 'LA LIBERTAD AVANZA' 'UNION PARA EL DESARROLLO SOCIAL - UDESO'
 'PROYECTO SUR' 'DEL CAMPO POPULAR' 'MOVIMIENTO AVANZADA SOCIALISTA'
 'FUERZA ORGANIZADA RENOVADORA DEMOCRATICA' 'GENTE EN ACCION'
 'MVTO AMPLIO DE TRABAJADORES Y JUBILADOS-MATRAJU'
 'FRENTE POPULAR DEMOCRATICO Y SOCIAL (PODEMOS)' 'CAMBIEMOS'
 'MOVIMIENTO AL SOCIALISMO' 'PATRIA GRANDE'
 'MST-MOVIMIENTO SOCIALISTA DE LOS TRABAJADORES' 'BANDERA VECINAL'
 'TODOS POR BUENOS AIRES' 'MOV. AMPLIO DE TRAB. Y JUBILADOS-MATRAJU'
 'IZQUIERDA AL FRENTE POR EL SOCIALISMO' 'FRENTE SOCIALISTA Y POPULAR'
 'CREO' 'FEDERAL' 'FRENTE PATRIOTA BANDERA VECINAL' 'HUMANISTA'
 'ENCUENTRO POPULAR POR TIERRA TECHO Y TRABAJO'
 'MOVIMIENTO ORGANIZACION DEMOCRATICA'
 'MOVIMIENTO AMPLIO DE TRABAJADORES Y JUBILADOS'
 'MOVIMIENTO DE AVANZADA SOCIALISTA' 'FRENTE PATRIOTA'
 'PARTIDO DIGNIDAD POPULAR' 'PARTIDO HUMANISTA'
 'PARTIDO RENOVADOR FEDERAL' 'PARTIDO REPUBLICANO FEDERAL'
 'MORAL Y PROGRESO' 'VOCACION SOCIAL' 'REPUBLICANO FEDERAL'
 'FRENTE UNION POR EL FUTURO' 'CELESTE PROVIDA' 'VERDE' 'POPULAR'
 'POLITICA OBRERA' 'PROYECTO JUSTO, SOCIAL Y HUMANISTA'
 'CONSERVADOR POPULAR' 'ESPERANZA DEL PUEBLO'
 'CORRIENTE DE PENSAMIENTO BONAERENSE' 'JUSTICIA Y DIGNIDAD PATRIOTICA'
 'UNIDAD SOCIAL' 'LABORISTA' 'HACEMOS POR NUESTRO PAIS'
 'PRINCIPIOS Y VALORES' 'MOVIMIENTO LIBRES DEL SUR'
 'MOVIMIENTO IZQUIERDA JUVENTUD Y DIGNIDAD' 'NUEVA UNION CELESTE'
 'FRENTE PATRIOTA FEDERAL' 'LIBERTARIO' 'BUENOS AIRES PRIMERO (BAP)'
 'CONSTRUYENDO PORVENIR' 'PROYECTO JOVEN' 'CONFIANZA PUBLICA'
 'POLITICA ABIERTA PARA LA INTEGRIDAD SOCIAL' 'FRENTE CÃ\x8dVICO Y SOCIAL'
 'PARTIDO DEMÃ“CRATA CRISTIANO' 'FRENTE CIVICO Y SOCIAL'
 'FRENTE TERCERA POSICION (F3P) UNIDAD CATAMARQUEÃ‘A' 'PARTIDO OBRERO'
 'FRENTE TERCERA POSICION' 'FRENTE JUSTICIALISTA PARA LA VICTORIA'
 'FRENTE CIVICO Y SOCIAL - CAMBIEMOS' 'FRENTE DE UNIDAD CIUDADANA'
 'OBRERO' 'FRENTE AMPLIO CATAMARQUEÑO' 'DEMOCRATA CRISTIANO'
 'FRENTE PROGRESISTA' 'UNIFICACION CIVICA REPUBLICANA'
 'MOVIMIENTO SOCIALISTA DE LOS TRABAJADORES' 'FRENTE CIVICO Y SOCIAL 2013'
 'MOVIMIENTO SOCIALISTA DE LOS TRABAJADORES (MST)' 'FRENTE AMPLIO PODEMOS'
 'MOVIMIENTO AUTENTICO POPULAR' 'RENACER POLITICO Y SOCIAL'
 'NACIONALISTA CONSTITUCIONAL -  UNIR' 'FRENTE UNIDOS POR LA GENTE'
 'FRENTE SOMOS CATAMARCA' 'UNION DEL CENTRO DEMOCRATICO' 'PARTIDO POPULAR'
 'AUTENTICOS LIBERALES CATAMARCA' 'PARTIDO POPULAR DE LA RECONSTRUCCIÃ“N'
 'UNION POR CHACO' 'UNIDOS POR UNA NUEVA ALTERNATIVA' 'DEL OBRERO'
 'PARTIDO CIUDADANOS A GOBERNAR' 'FRENTE CHACO MERECE MAS'
 'UN NUEVO PAIS (1P)' 'FUERZA PATRIA' 'ACCION CHAQUEÑA'
 'CHACO CAMBIA + JUNTOS POR EL CAMBIO' 'FRENTE INTEGRADOR'
 'UNION PARA EL DESARROLLO SOCIAL' 'POPULAR DE LA RECONSTRUCCION'
 'NACIONALISTA CONSTITUCIONAL - UNIR'
 'MVTO INDEPENDIENTE DE JUBILADOS Y DESOCUPADOS' 'FRENTE CIVICO PRO CHACO'
 'MOVIMIENTO INDEPENDIENTE JUSTICIA Y DIGNIDAD'
 'MOV.POL. SOCIAL Y CULTURAL PROYECTO SUR'
 'MOVIMIENTO POLITICO, SOCIAL Y CULTURAL PROYECTO SUR'
 'CIUDADANOS A GOBERNAR' 'DEMOCRATA' 'PARTIDO DEL OBRERO' 'UNIR'
 'ALTERNATIVA RENOVADORA FEDERAL' 'PARTIDO PROYECTO SUR CHACO'
 'VAMOS CON VOS' 'MOVIMIENTO IZQUIERDA JUVENTUD DIGNIDAD'
 'PARTIDO INDEPENDIENTE DE CHUBUT' 'UNIÃ“N CÃ\x8dVICA RADICAL'
 'MOVIMIENTO INDEPENDIENTE DE JUBILADOS Y DESOCUPADOS'
 'PARTIDO DE ACCION CHUBUTENSE' 'UNION CIVICA RADICAL'
 'MOVIMIENTO POLO SOCIAL LA TERCERA POSICION DE LA GENTE'
 'FRENTE UNION CHUBUT SOMOS TODOS' 'CAMBIEMOS CHUBUT'
 'FRENTE CHUBUT PARA TODOS' 'SOCIALISTA AUTENTICO DEL CHUBUT'
 'DEL TRABAJO Y DEL PUEBLO' 'JUNTOS POR EL CAMBIO CHUBUT'
 'MOVIMIENTO POLO SOCIAL CHUBUT' 'PARTIDO INDEPENDIENTE DEL CHUBUT'
 'INDEPENDIENTE DEL CHUBUT' 'CHUBUT SOMOS TODOS' 'DE ACCION CHUBUTENSE'
 'PARTIDO DEL TRABAJO Y DEL PUEBLO' 'CHUBUT AL FRENTE' 'GEN'
 'PRO - PROPUESTA REPUBLICANA' 'UNIÃ“N POPULAR' 'PARTIDO AUTONOMISTA'
 'PARTIDO DE LA CIUDAD EN ACCIÃ“N' 'UNION PRO' 'UNEN'
 'AUTODETERMINACION Y LIBERTAD' 'CAMINO POPULAR' 'VAMOS JUNTOS'
 'UNIDAD PORTEÃ‘A' 'EVOLUCION' 'AVANCEMOS HACIA 1PAIS MEJOR'
 'UNITE POR LA LIBERTAD Y LA DIGNIDAD' 'AUTODETERMINACIÓN Y LIBERTAD'
 'PRO PROPUESTA REPUBLICANA' 'UNION POPULAR' 'AUTONOMISTA'
 'DE LA CIUDAD EN ACCION' 'ACCION CIUDADANA' 'NUEVA IZQUIERDA'
 'EL MOVIMIENTO' 'MOVIMIENTO UNIDAD DEL TRABAJO Y LA PRODUCCION'
 'PARTIDO FE' 'PARTIDO FEDERAL'
 'INSTRUMENTO ELECTORAL POR LA UNIDAD POPULAR'
 'DE LA CULTURA LA EDUCACION Y EL TRABAJO'
 'FUERZA ORG. RENOV. DEMOCRATICA' 'CONVOCATORIA ABIERTA POR BUENOS AIRES'
 'RENOVADOR FEDERAL' 'SOCIALISTA AUTENTICO'
 'MOVIMIENTO DE JUBILADOS Y JUVENTUD' 'FRENTE RENOVADOR AUTENTICO'
 'SOCIALISTA AUTÉNTICO' 'POLÍTICA OBRERA' 'APTITUD RENOVADORA'
 'DIGNIDAD POPULAR' 'LA IZQUIERDA EN LA CIUDAD' 'REPUBLICANOS UNIDOS' 'FE'
 'UNION POR CORDOBA' 'VECINALISMO INDEPENDIENTE'
 'ENCUENTRO VECINAL CORDOBA' 'ES POSIBLE' 'FRENTE CORDOBA CIUDADANA'
 'PRIMERO LA GENTE' 'HACEMOS POR CORDOBA' 'UNION POPULAR FEDERAL'
 'JUSTICIALISTA' 'MOVIMIENTO DE ACCION VECINAL' 'UNION CELESTE Y BLANCO'
 'SOMOS' 'FRENTE DESPERTAR' 'HACEMOS POR CÓRDOBA'
 'ENCUENTRO VECINAL CÓRDOBA' 'UNIÓN POPULAR FEDERAL' 'DEMÓCRATA'
 'DE LA CONCERTACIÓN FORJA' 'HACEMOS POR NUESTRO PAÃ\x8dS'
 'FRENTE FEDERAL DE ACCION SOLIDARIA' 'ESTAMOS' 'LA LIBERTAD PRIMERO'
 'FRENTE FEDERAL' 'ENCUENTRO POR CORRIENTES' 'CAMBIO POPULAR'
 'ENCUENTRO POR CORRIENTES - ECO + CAMBIEMOS' 'JUNTOS PODEMOS MAS'
 'FRENTE RENOVADOR - 1PAIS' 'SOMOS CORRIENTES'
 'ENCUENTRO POR CORRIENTES - ECO + JUNTOS POR EL CAMBIO'
 'ECO + VAMOS CORRIENTES'
 'ENCUENTRO POR CORRIENTES - ECO+VAMOS CORRIENTES' 'CORRENTINA PANU-PA'
 'MST - NUEVA IZQUIERDA' 'MILES POR TIERRA, TECHO Y TRABAJO'
 'PARTIDO SOCIALISTA' 'UNIÃ“N PROVINCIAL COMPROMISO FEDERAL'
 'UNIÃ“N POR LA LIBERTAD' 'UNION POR ENTRE RIOS'
 'FRENTE JUSTICIALISTA SOMOS ENTRE RIOS' 'SOCIALISTA'
 'JUNTOS POR ENTRE RÍOS' 'MAS PARA ENTRE RIOS' 'JUNTOS POR ENTRE RIOS'
 'UNION PROVINCIAL COMPROMISO FEDERAL' 'UNION POR LA LIBERTAD' 'FORTALEZA'
 'ACUERDO REPUBLICANO FEDERAL' 'FRENTE AMPLIO FORMOSEÃ‘O'
 'FRENTE DE LA VICTORIA' 'FRENTE AMPLIO FORMOSEÃ‘O CAMBIEMOS'
 'PRINCIPIOS Y CONVICCION' 'FRENTE AMPLIO FORMOSEÃ‘O JUNTOS POR EL CAMBIO'
 'JUNTOS POR FORMOSA LIBRE' 'PRINCIPIOS Y CONVICCIÓN' 'ACCION NATIVA'
 'REPUBLICANA' 'FRENTE ESTAMOS CON VOS' 'LA NUEVA INDEPENDENCIA'
 'FRENTE PRIMERO JUJUY' 'FRENTE JUJEÃ‘O' 'FRENTE UNION PRO'
 'PARTIDO POR UN PUEBLO UNIDO' 'FRENTE CAMBIA JUJUY'
 'FRENTE JUJEÃ‘O CAMBIEMOS' 'FRENTE RENOVADOR 1PAIS'
 'MOVIMIENTO INTEGRACION LATINOAMERICANA DE EXPRESION SOCIAL'
 'CAMBIA JUJUY' 'POR UN PUEBLO UNIDO'
 'FRENTE PAMPEANO CÃ\x8dVICO Y SOCIAL (FREPAM)'
 'MOVIMIENTO DE INTEGRACIÃ“N Y DESARROLLO' 'PARTIDO JUSTICIALISTA'
 'FRENTE PAMPEANO CIVICO Y SOCIAL - FREPAM' 'FRENTE PROPUESTA FEDERAL'
 'PUEBLO NUEVO' 'PARTIDO DE LOS TRABAJADORES SOCIALISTAS'
 'PROPUESTA FREPAM' 'FRENTE CAMBIEMOS LA PAMPA'
 'FRENTE PROGRESISTA PAMPEANO' 'DE LOS TRABAJADORES SOCIALISTAS'
 'JUNTOS POR EL CAMBIO LA PAMPA'
 'FRENTE PAMPEANO, CIVICO Y SOCIAL (FREPAM)'
 'MOVIMIENTO DE INTEGRACION Y DESARROLLO'
 'FRENTE PARA LA VICTORIA RIOJANA' 'FRENTE POPULAR RIOJANO'
 'PRO-PROPUESTA REPUBLICANA' 'FUERZA CIVICA RIOJANA'
 'FRENTE NUEVO PACTO FEDERAL' 'IZQUIERDA POR UNA OPCION SOCIALISTA'
 'COMUNISTA' 'CAMBIEMOS - FUERZA CIVICA RIOJANA'
 'FRENTE JUSTICIALISTA RIOJANO' 'UNA RIOJA' 'ALTERNATIVA POPULAR RIOJANA'
 'MOVIMIENTO NORTE GRANDE' 'JUNTOS POR LA RIOJA' 'VAMOS LA RIOJA' 'UNIDOS'
 'UNION POR LA RIOJA' 'MOVIMIENTO DE INTEGRACION LATINOAMERICANA EXP.SOC'
 'FRENTE CAMBIEMOS' 'FRENTE CÃ\x8dVICO FEDERAL - UDESO MENDOZA'
 'IZQUIERDA DEL TRABAJADOR POR EL SOCIALISMO' 'UNION PD-PRO'
 'FRENTE AMPLIO PROGRESISTA-COALICION CIVICA-ARI'
 'FRENTE RENOVADOR FEDERAL DE LA ESPERANZA' 'SOMOS MENDOZA'
 'INTRANSIGENTE' 'CAMBIA MENDOZA' 'PROTECTORA FUERZA POLÃ\x8dTICA'
 'VAMOS ! MENDOCINOS' 'FRENTE CIVICO FEDERAL -UDESO MENDOZA'
 'CAMBIEMOS MENDOZA' 'FRENTE RENOVADOR FEDERAL POR LA ESPERANZA'
 'FRENTE SOMOS MENDOZA' 'ENCUENTRO POR MENDOZA' 'PODEMOS CON LA IZQUIERDA'
 'PROTECTORA FUERZA POLITICA' 'FRENTE RENOVADOR DE LA CONCORDIA'
 'FRENTE POPULAR UNIÃ“N PRO' 'FRENTE COMPROMISO FEDERAL' 'FRENTE UNIDOS'
 'PROYECTO POPULAR' 'NUEVO OCTUBRE' 'AGRARIO Y SOCIAL' 'FRENTE AVANCEMOS'
 'FRENTE JUNTOS POR EL CAMBIO' 'LIBERTAD, VALORES Y CAMBIO'
 'FRENTE RENOVADOR DE LA CONCORDIA - INNOVACION FEDERAL'
 'PARTIDO AGRARIO Y SOCIAL' 'POR LA JUSTICIA SOCIAL'
 'FRENTE DE LA ESPERANZA' 'FUERZA LIBERAL' 'MOVIMIENTO POPULAR NEUQUINO'
 'CAMBIA NEUQUEN' 'IZQUIERDA POR UNA OPCIÃ“N SOCIALISTA'
 'COMPROMISO CIVICO NEUQUINO' 'UNION DE LOS NEUQUINOS'
 'FRENTE PROGRESISTA SUR' 'UNIDAD CIUDADANA PARA LA VICTORIA'
 'FRENTE NEUQUINO' '1PAIS FRENTE RENOVADOR NEUQUEN +A' 'ARRIBA NEUQUEN'
 'PARTIDO MOVIMIENTO AL SOCIALISMO' 'CAMBIA NEUQUÉN'
 'LIBRES Y SOCIALISTAS' 'CAMBIEMOS RIO NEGRO' 'JUNTOS SOMOS RIO NEGRO'
 'PROVINCIAL RIONEGRINO' 'PARTIDO PROVINCIAL RIONEGRINO' 'FRENTE SALTEÃ‘O'
 'FRENTE POPULAR SALTEÃ‘O' 'SALTA SOMOS TODOS' 'PARTIDO DE LA VICTORIA'
 'PARTIDO RENOVADOR DE SALTA' 'FRENTE PLURAL'
 'MEMORIA Y MOVILIZACION SOCIAL' 'CAMBIEMOS SALTA' 'CAMBIEMOS PAIS'
 'FRENTE UNIDAD Y RENOVACION' 'FRENTE CIUDADANO PARA LA VICTORIA'
 'FRENTE POPULAR PARA LA LIBERACION' 'UNION POR SALTA'
 'PARTIDO CONSERVADOR POPULAR' 'JUNTOS POR EL CAMBIO +' 'FRENTE SI + PRS'
 'UNIDOS POR SALTA' 'FELICIDAD' 'AHORA PATRIA' 'SI - SALTA INDEPENDIENTE'
 'UNION POR LA REPUBLICA - FRENTE POR LA JUSTICIA'
 'DE TRABAJADORES POR EL SOCIALISMO' 'PARTIDO DIGNIDAD CIUDADANA'
 'CRUZADA RENOVADORA' 'FRENTE DEL PUEBLO' 'COMPROMISO CON SAN JUAN'
 'FRENTE TODOS' 'CAMBIEMOS SAN JUAN' '1 PAIS SOMOS SAN JUAN'
 'ADN - ACCION POR UNA DEMOCRACIA NUEVA' 'FRENTE PROGRESISTA POPULAR'
 'NUEVA DIRIGENCIA' 'FRENTE DE TODOS - TODOS SAN JUAN'
 'CONSENSO ISCHIGUALASTO' 'DIGNIDAD CIUDADANA' 'CAMBIEMOS POR SAN JUAN'
 '1 PAIS - SOMOS SAN JUAN' 'ACCION POR UNA DEMOCRACIA NUEVA'
 'MOVIMIENTO DE VIDA Y COMPROMISO' 'CONSENSO ISHCHIGUALASTO'
 'LIBRES DEL SUR' 'DEMOCRATA INDEPENDIENTE'
 'FRENTE UNIDAD JUSTICIALISTA SAN LUIS' 'AVANZAR Y CAMBIEMOS POR SAN LUIS'
 'UNIDOS POR SAN LUIS' 'FUERZA SAN LUIS' 'UNIÓN CÍVICA RADICAL'
 'TODOS UNIDOS' 'UNION POR SAN LUIS' 'UNION Y LIBERTAD'
 'UNIÃ“N Y LIBERTAD' 'FRENTE ENCUENTRO SUR' 'UNION PARA VIVIR MEJOR'
 'UNION PARA VIVIR MEJOR - CAMBIEMOS'
 'FRENTE DE IZQUIERDA Y DE LOS TRABAJADORES - PARTIDO OBRERO + IZQUIERDA POR UNA OPCION SOCIALISTA'
 'CAMBIA SANTA CRUZ' 'SOMOS ENERGIA PARA RENOVAR SANTA CRUZ -SER-'
 'POR SANTA CRUZ' 'SOMOS ENERGÍA PARA RENOVAR SANTA CRUZ -SER-'
 'MOVIMIENTO INDEPENDIENTE RENOVADOR' 'UNION PRO SANTA FE FEDERAL'
 'SANTAFESINO CIEN POR CIENTO'
 'UNITE! CON FE POR LA CULTURA, EDUCACION Y TRABAJO'
 '1 PROYECTO SANTAFESINO' 'CIUDAD FUTURA' 'FRENTE SOCIAL Y POPULAR'
 'ESPACIO GRANDE' 'FRENTE NOS' 'SOBERANIA POPULAR' 'SOMOS FUTURO'
 'PODEMOS' 'PRIMERO SANTA FE' 'LA FUERZA DE SANTA FE'
 'DE TRABAJADORES POR EL SOCIALISMO (PTS)' 'UNION CELESTE Y BLANCA'
 'ALTERNATIVA FEDERAL' 'LEALTAD Y DIGNIDAD'
 'FRENTE AMPLIO POR LA SOBERANIA' 'NUEVO RUMBO'
 'POLITICA ABIERTA PARA LA INTEGRIDAD SOCIAL (PAIS)'
 'ENCUENTRO REPUBLICANO FEDERAL' 'FRENTE CÃ\x8dVICO POR SANTIAGO'
 'FRENTE CIVICO POR SANTIAGO' 'FRENTE CIVICO PARA LA VICTORIA'
 'FRENTE PATRIOTICO LABORISTA' 'POR UN SANTIAGO OBRERO'
 'FRENTE POR LA LIBERTAD' 'TRES BANDERAS' 'MOVIMIENTO POPULAR FUEGUINO'
 'ENCUENTRO POPULAR' 'PARTIDO SOCIAL PATAGÃ“NICO'
 'MOVIMIENTO SOLIDARIO POPULAR' 'UNION FEDERAL'
 'ESPACIO DEMOCRATICO PARA LA VICTORIA' 'CAMBIEMOS TIERRA DEL FUEGO'
 'SOCIAL PATAGONICO' 'FRENTE CIUDADANO Y SOCIAL' 'FRENTE TIERRA DE UNION'
 'FEDERAL FUEGUINO' 'INICIATIVA POR LA UNION'
 'JUNTOS POR EL CAMBIO TIERRA DEL FUEGO' 'VAMOS TODOS A VIVIR MEJOR'
 'PARTIDO SOCIAL PATAGONICO' 'SOMOS FUEGUINOS' 'JUNTOS POR EL CAMBIO TDF'
 'UNIR TDF' 'PARTIDO CAMBIO POPULAR TUCUMANO'
 'MOVIMIENTO DE PARTICIPACIÃ“N CIUDADANA' 'FRENTE ACUERDO CIVICO Y SOCIAL'
 'FUERZA REPUBLICANA' 'ALTERNATIVA POPULAR'
 'LABORISTA DE LA INDEPENDENCIA'
 'PARTIDO MOVIMIENTO DE PARTICIPACION CIUDADANA'
 'FRENTE JUSTICIALISTA POR TUCUMAN' 'CAMBIEMOS PARA EL BICENTENARIO'
 'JUNTOS POR EL CAMBIO JXC' 'FRENTE AMPLIO POR TUCUMÁN'
 'CAMBIO POPULAR TUCUMANO' 'MOVIMIENTO DE PARTICIPACION CIUDADANA'
 'VOS CAMBIO Y ACCION' 'FRENTE AMPLIO TUCUMANO' 'FRENTE GRANDE'
 'ACUERDO FEDERAL']

> 2011 – 2015	Frente para la Victoria (FPV)	Elecciones Presidenciales 2011 (re-elección de C. F. de Kirchner) y 2015 (candidatura de Daniel Scioli).

>2017	Unidad Ciudadana (UC)	Elecciones Legislativas de 2017 (en la provincia de Buenos Aires, liderada por C. F. de Kirchner). Aunque el FPV se mantuvo como alianza en otras provincias.

>2019 – 2023	Frente de Todos (FdT)	Elecciones Presidenciales 2019 (gobierno de Alberto Fernández).

>2023 – 2025	Unión por la Patria (UxP)	Elecciones Presidenciales 2023 (candidatura de Sergio Massa).

>2025 – Actualidad	Fuerza Patria (FP)	Adopción del nombre a partir de 2025, principalmente para las elecciones legislativas de ese año, reemplazando a Unión por la Patria (específicación sólo mencionada por ser parte de la última modificación en la coalición, que no la utilizamos por quedar fuera del espacio temporal elegido)

In [ ]:
peronismo= ("UNIDAD CIUDADANA", "FRENTE DE TODOS","UNION POR LA PATRIA","FRENTE PARA LA VICTORIA","ALIANZA FRENTE PARA LA VICTORIA", "FRENTE PARA LA VICTORIA RIOJANA", "FRENTE JUSTICIALISTA", "FRENTE JUSTICIALISTA PARA LA VICTORIA", "PARTIDO DE LA VICTORIA","ALIANZA PARA LA VICTORIA","FUERZA PATRIA","MOVIMIENTO POLO SOCIAL LA TERCERA POSICION DE LA GENTE","PARTIDO JUSTICIALISTA")

In [ ]:
presidenciales= ("GENERALES 2011","GENERALES 2013", "GENERALES 2015","GENERALES 2017" "GENERALES 2019","GENERALES 2021", "GENERALES 2023" )

In [ ]:
tabla_filtrada_nueva = elecciones[elecciones["Elecciones"].isin(presidenciales)]

In [ ]:
tabla_filtrada_nueva= tabla_filtrada_nueva[tabla_filtrada_nueva["Partido"].isin(peronismo)]

In [ ]:
tabla_filtrada_nueva

,id,Elecciones,Partido,Porcentaje,Votos,Participacion,Electores,Votantes,Bancas
0,BUENOS AIRES,GENERALES 2011,FRENTE PARA LA VICTORIA,56.97,4460986.0,123.315,10574461,8693248,NaN
11,BUENOS AIRES,GENERALES 2013,FRENTE PARA LA VICTORIA,32.29,2881966.0,83.050,11453499,9512594,NaN
19,BUENOS AIRES,GENERALES 2015,FRENTE PARA LA VICTORIA,37.14,3212919.0,78.580,12033279,9455259,NaN
43,BUENOS AIRES,GENERALES 2021,FRENTE DE TODOS,38.53,3368310.0,72.890,12530612,9133379,15.0
51,BUENOS AIRES,GENERALES 2023,UNION POR LA PATRIA,43.65,3993120.0,77.430,13124435,10161648,16.0
...,...,...,...,...,...,...,...,...,...
3081,TUCUMAN,GENERALES 2011,FRENTE PARA LA VICTORIA,60.91,456466.0,79.620,1008987,803357,NaN
3091,TUCUMAN,GENERALES 2013,FUERZA PATRIA,46.93,416962.0,84.560,1.077.635,911237,NaN
3101,TUCUMAN,GENERALES 2015,FRENTE PARA LA VICTORIA,51.38,404652.0,80.610,1154195,930350,NaN
3123,TUCUMAN,GENERALES 2021,FRENTE DE TODOS,42.16,406411.0,79.620,1266757,1008613,2.0
3131,TUCUMAN,GENERALES 2023,UNION POR LA PATRIA,"46,99",437312.0,80.030,1319493,1055954,3.0

In [ ]:
tabla_filtrada_nueva["anio"] = tabla_filtrada_nueva["Elecciones"].str.extract(r'(\d{4})')

In [ ]:
Cordoba= ('CORDOBA', 'cordoba', 'CORDOBA','CORD OBA', 'Córdoba' )
elecciones["id"] = elecciones["id"].str.strip().str.replace("Ã“", "Ó").str.replace("Ã‘", "Ñ").str.title()
elecciones["id"] = elecciones["id"].replace({"Cord Oba": "Cordoba"})

In [ ]:
print(tabla_filtrada_nueva ['id'].unique())

['BUENOS AIRES' 'CATAMARCA' 'CHACO' 'CHUBUT'
 'CIUDAD AUTONOMA DE BUENOS AIRES' 'CORDOBA' 'Córdoba' 'CORDOBA '
 'CORRIENTES' 'ENTRE RIOS' 'FORMOSA' 'JUJUY' 'LA PAMPA' 'LA RIOJA'
 'MENDOZA' 'MISIONES' 'NEUQUEN' 'RIO NEGRO' 'SALTA' 'SAN JUAN' 'SAN LUIS'
 'SANTA CRUZ' 'SANTA FE' 'SANTIAGO DEL ESTERO' 'TIERRA DEL FUEGO'
 'TUCUMAN']

In [ ]:
print(tabla_filtrada_nueva ['anio'].unique())

['2011' '2013' '2015' '2021' '2023']

In [ ]:
tabla_filtrada_nueva['Participacion']=tabla_filtrada_nueva['Participacion'].astype(int)

In [ ]:
tabla_filtrada_nueva['Participacion'] = tabla_filtrada_nueva['Participacion'].astype(str).str.replace(',', '.', regex=False).astype(float)

min_valor = tabla_filtrada_nueva['Participacion'].min()
max_valor = tabla_filtrada_nueva['Participacion'].max()

tabla_filtrada_nueva['Participacion'] = ((tabla_filtrada_nueva['Participacion'] - min_valor) / (max_valor - min_valor)) * 100

pd.set_option("display.float_format", "{:.2f}".format)

In [ ]:
tabla_filtrada_nueva

,id,Elecciones,Partido,Porcentaje,Votos,Participacion,Electores,Votantes,Bancas,anio
0,BUENOS AIRES,GENERALES 2011,FRENTE PARA LA VICTORIA,56.97,4460986.00,53.57,10574461,8693248,NaN,2011
11,BUENOS AIRES,GENERALES 2013,FRENTE PARA LA VICTORIA,32.29,2881966.00,17.86,11453499,9512594,NaN,2013
19,BUENOS AIRES,GENERALES 2015,FRENTE PARA LA VICTORIA,37.14,3212919.00,13.39,12033279,9455259,NaN,2015
43,BUENOS AIRES,GENERALES 2021,FRENTE DE TODOS,38.53,3368310.00,8.04,12530612,9133379,15.00,2021
51,BUENOS AIRES,GENERALES 2023,UNION POR LA PATRIA,43.65,3993120.00,12.50,13124435,10161648,16.00,2023
...,...,...,...,...,...,...,...,...,...,...
3081,TUCUMAN,GENERALES 2011,FRENTE PARA LA VICTORIA,60.91,456466.00,14.29,1008987,803357,NaN,2011
3091,TUCUMAN,GENERALES 2013,FUERZA PATRIA,46.93,416962.00,18.75,1.077.635,911237,NaN,2013
3101,TUCUMAN,GENERALES 2015,FRENTE PARA LA VICTORIA,51.38,404652.00,15.18,1154195,930350,NaN,2015
3123,TUCUMAN,GENERALES 2021,FRENTE DE TODOS,42.16,406411.00,14.29,1266757,1008613,2.00,2021
3131,TUCUMAN,GENERALES 2023,UNION POR LA PATRIA,"46,99",437312.00,15.18,1319493,1055954,3.00,2023

In [ ]:
print(tabla_filtrada_nueva.isnull().sum())

id                0
Elecciones        0
Partido           0
Porcentaje        0
Votos             0
Participacion     0
Electores         0
Votantes          0
Bancas           75
anio              0
dtype: int64

In [ ]:
tabla_filtrada_nueva['Electores'] = tabla_filtrada_nueva['Electores'].astype(str).str.replace('.', '', regex=False).astype(float)
tabla_filtrada_nueva['Votantes'] = tabla_filtrada_nueva['Votantes'].astype(str).str.replace('.', '', regex=False).astype(float)

In [ ]:
tabla_filtrada_nueva.dtypes

id                object
Elecciones        object
Partido           object
Porcentaje        object
Votos            float64
Participacion    float64
Electores        float64
Votantes         float64
Bancas           float64
anio              object
dtype: object

**1. Porcentaje Obtenido** (Sobre Votos Válidos o Afirmativos)
Este es el porcentaje que se anuncia más comúnmente en los medios y determina quién gana la elección.

Denominador (Base 100%): El total de votos válidos o, más específicamente, el total de votos afirmativos para una categoría de cargo (excluyendo votos en blanco y nulos).

Qué Mide: Mide la preferencia o el ***respaldo de un partido entre aquellos ciudadanos que efectivamente votaron*** y lo hicieron de forma válida.

**2. Proporción sobre el Padrón** (Sobre Electores Habilitados)
Esta proporción se utiliza para medir el alcance y el impacto real de un partido dentro del total de la población habilitada para votar.

Denominador (Base 100%): El Padrón Electoral (el número total de ciudadanos habilitados para votar en esa jurisdicción, sin importar si votaron o no).

Qué Mide: Mide el respaldo potencial o la** fuerza estructural de un partido en relación con todo el universo de electores, incluidos los que se abstuvieron.**

In [ ]:
('/nPromedio voto x elector')
tabla_filtrada_nueva['promedio_porcentual'] = (tabla_filtrada_nueva['Votos'] / tabla_filtrada_nueva['Electores']) * 100

tabla_filtrada_nueva['promedio_porcentual'] = tabla_filtrada_nueva['promedio_porcentual'].round(2)

In [ ]:
tabla_filtrada_nueva['Votos'] = tabla_filtrada_nueva['Votos'].apply(lambda x: f"{x:,.0f}".replace(",", "."))
tabla_filtrada_nueva['Electores'] = tabla_filtrada_nueva['Electores'].apply(lambda x: f"{x:,.0f}".replace(",", "."))
tabla_filtrada_nueva['Votantes'] = tabla_filtrada_nueva['Votantes'].apply(lambda x: f"{x:,.0f}".replace(",", "."))

In [ ]:
tabla_filtrada_nueva['Bancas'] =tabla_filtrada_nueva['Bancas'].round(0).astype('Int64')
tabla_filtrada_nueva['Bancas'] = tabla_filtrada_nueva['Bancas'].astype('Int64')
tabla_filtrada_nueva['Bancas'] = tabla_filtrada_nueva['Bancas'].fillna(0)

In [ ]:
tabla_filtrada_nueva

,id,Elecciones,Partido,Porcentaje,Votos,Participacion,Electores,Votantes,Bancas,anio,promedio_porcentual
0,BUENOS AIRES,GENERALES 2011,FRENTE PARA LA VICTORIA,56.97,4.460.986,53.57,10.574.461,8.693.248,0,2011,42.19
11,BUENOS AIRES,GENERALES 2013,FRENTE PARA LA VICTORIA,32.29,2.881.966,17.86,11.453.499,9.512.594,0,2013,25.16
19,BUENOS AIRES,GENERALES 2015,FRENTE PARA LA VICTORIA,37.14,3.212.919,13.39,12.033.279,9.455.259,0,2015,26.70
43,BUENOS AIRES,GENERALES 2021,FRENTE DE TODOS,38.53,3.368.310,8.04,12.530.612,9.133.379,15,2021,26.88
51,BUENOS AIRES,GENERALES 2023,UNION POR LA PATRIA,43.65,3.993.120,12.50,13.124.435,10.161.648,16,2023,30.43
...,...,...,...,...,...,...,...,...,...,...,...
3081,TUCUMAN,GENERALES 2011,FRENTE PARA LA VICTORIA,60.91,456.466,14.29,1.008.987,803.357,0,2011,45.24
3091,TUCUMAN,GENERALES 2013,FUERZA PATRIA,46.93,416.962,18.75,1.077.635,911.237,0,2013,38.69
3101,TUCUMAN,GENERALES 2015,FRENTE PARA LA VICTORIA,51.38,404.652,15.18,1.154.195,930.350,0,2015,35.06
3123,TUCUMAN,GENERALES 2021,FRENTE DE TODOS,42.16,406.411,14.29,1.266.757,1.008.613,2,2021,32.08
3131,TUCUMAN,GENERALES 2023,UNION POR LA PATRIA,"46,99",437.312,15.18,1.319.493,1.055.954,3,2023,33.14

In [ ]:
tabla_filtrada_nueva.dtypes

id                      object
Elecciones              object
Partido                 object
Porcentaje              object
Votos                   object
Participacion          float64
Electores               object
Votantes                object
Bancas                   Int64
anio                    object
promedio_porcentual    float64
dtype: object

In [ ]:
tabla_filtrada_nueva= tabla_filtrada_nueva.rename(columns={
      'promedio_porcentual': 'prop. sobre padron',
      'anio': 'Año',
      'id': 'Provincias'
      })

In [ ]:
tabla_filtrada_nueva["Participacion"] = tabla_filtrada_nueva["Participacion"].astype(str).str.replace('%', '', regex=False).astype(float).apply(lambda x: f"{x:.2f}%")
tabla_filtrada_nueva["prop. sobre padron"] = tabla_filtrada_nueva["prop. sobre padron"].astype(str).str.replace('%', '', regex=False).astype(float).apply(lambda x: f"{x:.2f}%")
tabla_filtrada_nueva["Porcentaje"] = tabla_filtrada_nueva["Porcentaje"].astype(str).str.replace(',', '.', regex=False).astype(float).apply(lambda x: f"{x:.2f}%")

In [ ]:
tabla_filtrada_nueva

,Provincias,Elecciones,Partido,Porcentaje,Votos,Participacion,Electores,Votantes,Bancas,Año,prop. sobre padron
0,BUENOS AIRES,GENERALES 2011,FRENTE PARA LA VICTORIA,56.97%,4.460.986,53.57%,10.574.461,8.693.248,0,2011,42.19%
11,BUENOS AIRES,GENERALES 2013,FRENTE PARA LA VICTORIA,32.29%,2.881.966,17.86%,11.453.499,9.512.594,0,2013,25.16%
19,BUENOS AIRES,GENERALES 2015,FRENTE PARA LA VICTORIA,37.14%,3.212.919,13.39%,12.033.279,9.455.259,0,2015,26.70%
43,BUENOS AIRES,GENERALES 2021,FRENTE DE TODOS,38.53%,3.368.310,8.04%,12.530.612,9.133.379,15,2021,26.88%
51,BUENOS AIRES,GENERALES 2023,UNION POR LA PATRIA,43.65%,3.993.120,12.50%,13.124.435,10.161.648,16,2023,30.43%
...,...,...,...,...,...,...,...,...,...,...,...
3081,TUCUMAN,GENERALES 2011,FRENTE PARA LA VICTORIA,60.91%,456.466,14.29%,1.008.987,803.357,0,2011,45.24%
3091,TUCUMAN,GENERALES 2013,FUERZA PATRIA,46.93%,416.962,18.75%,1.077.635,911.237,0,2013,38.69%
3101,TUCUMAN,GENERALES 2015,FRENTE PARA LA VICTORIA,51.38%,404.652,15.18%,1.154.195,930.350,0,2015,35.06%
3123,TUCUMAN,GENERALES 2021,FRENTE DE TODOS,42.16%,406.411,14.29%,1.266.757,1.008.613,2,2021,32.08%
3131,TUCUMAN,GENERALES 2023,UNION POR LA PATRIA,46.99%,437.312,15.18%,1.319.493,1.055.954,3,2023,33.14%

In [ ]:
tabla_filtrada_nueva['Año'] = tabla_filtrada_nueva['Año'].astype(int)

In [ ]:
import os

# Define the directory path and the full file path
output_dir = '/content/drive/MyDrive/tp final Anal datos'
output_file = os.path.join(output_dir, 'tabla_filtrada_nueva_copia.csv')

# Create the directory if it doesn't exist
os.makedirs(output_dir, exist_ok=True)

# Save the DataFrame to the specified path
tabla_filtrada_nueva_copia.to_csv(output_file, index=False)

print(f"Archivo guardado exitosamente en: {output_file}")

Archivo guardado exitosamente en: /content/drive/MyDrive/tp final Anal datos/tabla_filtrada_nueva_copia.csv

In [ ]:
tabla_filtrada_nueva_copia = tabla_filtrada_nueva[tabla_filtrada_nueva["Elecciones"] == "GENERALES 2013"].copy()

In [ ]:
tabla_filtrada_nueva_copia

,Provincias,Elecciones,Partido,Porcentaje,Votos,Participacion,Electores,Votantes,Bancas,Año,prop. sobre padron
11,BUENOS AIRES,GENERALES 2013,FRENTE PARA LA VICTORIA,32.29%,2.881.966,17.86%,11.453.499,9.512.594,0,2013,25.16%
203,CATAMARCA,GENERALES 2013,FRENTE PARA LA VICTORIA,38.73%,75.640,9.82%,278.208,208.462,0,2013,27.19%
320,CHACO,GENERALES 2013,FRENTE PARA LA VICTORIA,59.30%,350.471,13.39%,815.434,639.446,0,2013,42.98%
455,CHUBUT,GENERALES 2013,MOVIMIENTO POLO SOCIAL LA TERCERA POSICION DE ...,4.71%,13.665,12.50%,392.901,304.357,0,2013,3.48%
761,Córdoba,GENERALES 2013,FRENTE PARA LA VICTORIA,15.26%,304.658,14.29%,2.651.940,2.111.752,0,2013,11.49%
930,CORRIENTES,GENERALES 2013,FUERZA PATRIA,42.73%,238.648,10.71%,765.203,580.610,0,2013,31.19%
1040,ENTRE RIOS,GENERALES 2013,FRENTE PARA LA VICTORIA,46.61%,358.886,22.32%,906.072,799.384,0,2013,39.61%
1152,FORMOSA,GENERALES 2013,FRENTE PARA LA VICTORIA,60.07%,147.165,30.36%,394.536,257.445,0,2013,37.30%
1256,JUJUY,GENERALES 2013,FRENTE PARA LA VICTORIA,38.96%,9.260,8.93%,479.057,354.359,0,2013,1.93%
1374,LA PAMPA,GENERALES 2013,PARTIDO JUSTICIALISTA,35.15%,70.866,14.29%,261.967,208.319,0,2013,27.05%
1487,LA RIOJA,GENERALES 2013,FRENTE PARA LA VICTORIA,47.01%,87.658,13.39%,254.651,199.415,0,2013,34.42%
1615,MENDOZA,GENERALES 2013,FRENTE PARA LA VICTORIA,27.15%,274.457,15.18%,1.310.378,1.049.070,0,2013,20.94%
1747,MISIONES,GENERALES 2013,FRENTE PARA LA VICTORIA,11.27%,67.542,15.18%,787.676,637.375,0,2013,8.57%
1884,NEUQUEN,GENERALES 2013,FRENTE PARA LA VICTORIA,21.21%,70.372,16.07%,437.030,355.573,0,2013,16.10%
2013,RIO NEGRO,GENERALES 2013,FRENTE PARA LA VICTORIA,50.75%,171.632,11.61%,476.519,363.291,0,2013,36.02%
2134,SALTA,GENERALES 2013,PARTIDO JUSTICIALISTA,19.04%,118.229,7.14%,886.432,636.196,0,2013,13.34%
2136,SALTA,GENERALES 2013,PARTIDO DE LA VICTORIA,7.62%,47.315,7.14%,886.432,636.196,0,2013,5.34%
2276,SAN JUAN,GENERALES 2013,FRENTE PARA LA VICTORIA,55.33%,224.314,16.96%,506.772,416.817,0,2013,44.26%
2399,SAN LUIS,GENERALES 2013,FRENTE PARA LA VICTORIA,17.90%,40.473,12.50%,334.096,258.865,0,2013,12.11%
2513,SANTA CRUZ,GENERALES 2013,FRENTE PARA LA VICTORIA,24.74%,39.284,8.93%,222.657,164.169,0,2013,17.64%
2514,SANTA CRUZ,GENERALES 2013,PARTIDO JUSTICIALISTA,20.04%,31.834,8.93%,222.657,164.169,0,2013,14.30%
2629,SANTA FE,GENERALES 2013,FRENTE PARA LA VICTORIA,22.68%,427.459,100.00%,1.695.907,1.983.872,0,2013,25.21%
2812,SANTIAGO DEL ESTERO,GENERALES 2013,FRENTE PARA LA VICTORIA,4.60%,20.580,9.82%,652.211,484.553,0,2013,3.16%
2941,TIERRA DEL FUEGO,GENERALES 2013,FRENTE PARA LA VICTORIA,27.31%,20.325,41.07%,116.458,85.008,0,2013,17.45%
2950,TIERRA DEL FUEGO,GENERALES 2013,PARTIDO JUSTICIALISTA,3.57%,2.655,8.04%,116.458,85.008,0,2013,2.28%
3091,TUCUMAN,GENERALES 2013,FUERZA PATRIA,46.93%,416.962,18.75%,1.077.635,911.237,0,2013,38.69%

DASHBOARD EN LOOKER STUDIO (tambien se encuentra el pdf en el mi portfolio de drive)
https://datastudio.google.com/reporting/4b697a70-3a3a-49dc-87aa-82358a4c60e7/page/p_0qwy9nwayd/edit